// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Board struct {
	ID     string   `json:"id"`
	Title  string   `json:"title"`
	Shapes []*Shape `json:"shapes"`
}

type CursorPresence struct {
	ClientID string  `json:"clientID"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
}

type LockEvent struct {
	ShapeID  string     `json:"shapeId"`
	ClientID string     `json:"clientID"`
	Action   LockAction `json:"action"`
}

type Mutation struct {
}

type Query struct {
}

type Shape struct {
	ID          string    `json:"id"`
	BoardID     string    `json:"boardId"`
	Type        ShapeType `json:"type"`
	X           float64   `json:"x"`
	Y           float64   `json:"y"`
	Width       float64   `json:"width"`
	Height      float64   `json:"height"`
	Text        *string   `json:"text,omitempty"`
	Rotation    float64   `json:"rotation"`
	ZIndex      int       `json:"zIndex"`
	Locked      bool      `json:"locked"`
	Fill        *string   `json:"fill,omitempty"`
	Stroke      *string   `json:"stroke,omitempty"`
	StrokeWidth *float64  `json:"strokeWidth,omitempty"`
}

type ShapeEvent struct {
	Type     ShapeEventType `json:"type"`
	Shape    *Shape         `json:"shape"`
	ClientID string         `json:"clientID"`
}

type ShapeInput struct {
	ID          string     `json:"id"`
	Type        *ShapeType `json:"type,omitempty"`
	X           *float64   `json:"x,omitempty"`
	Y           *float64   `json:"y,omitempty"`
	Width       *float64   `json:"width,omitempty"`
	Height      *float64   `json:"height,omitempty"`
	Text        *string    `json:"text,omitempty"`
	Rotation    *float64   `json:"rotation,omitempty"`
	ZIndex      *int       `json:"zIndex,omitempty"`
	Locked      *bool      `json:"locked,omitempty"`
	Fill        *string    `json:"fill,omitempty"`
	Stroke      *string    `json:"stroke,omitempty"`
	StrokeWidth *float64   `json:"strokeWidth,omitempty"`
}

type Subscription struct {
}

type TransientShape struct {
	ID       string   `json:"id"`
	X        *float64 `json:"x,omitempty"`
	Y        *float64 `json:"y,omitempty"`
	Width    *float64 `json:"width,omitempty"`
	Height   *float64 `json:"height,omitempty"`
	ClientID string   `json:"clientID"`
}

type TransientShapeInput struct {
	ID     string   `json:"id"`
	X      *float64 `json:"x,omitempty"`
	Y      *float64 `json:"y,omitempty"`
	Width  *float64 `json:"width,omitempty"`
	Height *float64 `json:"height,omitempty"`
}

type TransientShapesBatch struct {
	Shapes   []*TransientShape `json:"shapes"`
	ClientID string            `json:"clientID"`
}

type LockAction string

const (
	LockActionAcquire LockAction = "ACQUIRE"
	LockActionRelease LockAction = "RELEASE"
)

var AllLockAction = []LockAction{
	LockActionAcquire,
	LockActionRelease,
}

func (e LockAction) IsValid() bool {
	switch e {
	case LockActionAcquire, LockActionRelease:
		return true
	}
	return false
}

func (e LockAction) String() string {
	return string(e)
}

func (e *LockAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LockAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LockAction", str)
	}
	return nil
}

func (e LockAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LockAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LockAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShapeEventType string

const (
	ShapeEventTypeCreated ShapeEventType = "CREATED"
	ShapeEventTypeUpdated ShapeEventType = "UPDATED"
	ShapeEventTypeDeleted ShapeEventType = "DELETED"
)

var AllShapeEventType = []ShapeEventType{
	ShapeEventTypeCreated,
	ShapeEventTypeUpdated,
	ShapeEventTypeDeleted,
}

func (e ShapeEventType) IsValid() bool {
	switch e {
	case ShapeEventTypeCreated, ShapeEventTypeUpdated, ShapeEventTypeDeleted:
		return true
	}
	return false
}

func (e ShapeEventType) String() string {
	return string(e)
}

func (e *ShapeEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShapeEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShapeEventType", str)
	}
	return nil
}

func (e ShapeEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShapeEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShapeEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ShapeType string

const (
	ShapeTypeRect    ShapeType = "RECT"
	ShapeTypeEllipse ShapeType = "ELLIPSE"
	ShapeTypeText    ShapeType = "TEXT"
	ShapeTypeSticker ShapeType = "STICKER"
)

var AllShapeType = []ShapeType{
	ShapeTypeRect,
	ShapeTypeEllipse,
	ShapeTypeText,
	ShapeTypeSticker,
}

func (e ShapeType) IsValid() bool {
	switch e {
	case ShapeTypeRect, ShapeTypeEllipse, ShapeTypeText, ShapeTypeSticker:
		return true
	}
	return false
}

func (e ShapeType) String() string {
	return string(e)
}

func (e *ShapeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ShapeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ShapeType", str)
	}
	return nil
}

func (e ShapeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ShapeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ShapeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
