// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server

type Board struct {
	ID     string   `json:"id"`
	Title  string   `json:"title"`
	Shapes []*Shape `json:"shapes"`
}

type Query struct {
}

type Shape struct {
	ID      string  `json:"id"`
	BoardID string  `json:"boardId"`
	Type    string  `json:"type"`
	X       float64 `json:"x"`
	Y       float64 `json:"y"`
	Width   float64 `json:"width"`
	Height  float64 `json:"height"`
	Text    *string `json:"text,omitempty"`
}
