package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"server/graph"
	"server/presence"
)

// UpdateCursor is the resolver for the updateCursor field.
func (r *mutationResolver) UpdateCursor(ctx context.Context, boardID string, clientID string, x float64, y float64) (bool, error) {
	presence.Publish(boardID, &graph.CursorPresence{
		ClientID: clientID,
		X:        x,
		Y:        y,
	})
	return true, nil
}

// CursorsMoved is the resolver for the cursorsMoved field.
func (r *subscriptionResolver) CursorsMoved(ctx context.Context, boardID string) (<-chan *graph.CursorPresence, error) {
	ch := make(chan *graph.CursorPresence, 1)
	presence.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		presence.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
