package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"server/graph"
	"server/locks"
	"server/storage"
	"server/subscriptions"
	"server/transient"
)

// UpdateShape is the resolver for the updateShape field.
func (r *mutationResolver) UpdateShape(ctx context.Context, boardID string, shape graph.ShapeInput, clientID string) (*graph.Shape, error) {
	storage.BoardsMu.Lock()
	defer storage.BoardsMu.Unlock()

	board, exists := storage.Boards[boardID]
	if !exists {
		board = &graph.Board{
			ID:     boardID,
			Title:  "New Board",
			Shapes: []*graph.Shape{},
		}
		storage.Boards[boardID] = board
	}

	var existing *graph.Shape
	for _, s := range board.Shapes {
		if s.ID == shape.ID {
			existing = s
			break
		}
	}

	eventType := graph.ShapeEventTypeUpdated

	if existing == nil {
		existing = &graph.Shape{
			ID:       shape.ID,
			BoardID:  boardID,
			Rotation: 0,
			ZIndex:   0,
			Locked:   false,
		}
		board.Shapes = append(board.Shapes, existing)

		eventType = graph.ShapeEventTypeCreated
	}

	// применяем PATCH (ShapeInput -> Shape)
	storage.ApplyShapePatch(existing, shape)

	// шлём событие
	subscriptions.Publish(boardID, &graph.ShapeEvent{
		Type:     eventType,
		Shape:    existing,
		ClientID: clientID,
	})

	return existing, nil
}

// MoveShapeTransient is the resolver for the moveShapeTransient field.
func (r *mutationResolver) MoveShapeTransient(ctx context.Context, boardID string, shape graph.TransientShapeInput, clientID string) (bool, error) {
	ts := &graph.TransientShape{
		ID:       shape.ID,
		X:        shape.X,
		Y:        shape.Y,
		Width:    shape.Width,
		Height:   shape.Height,
		ClientID: clientID,
	}

	// Публикуем в transient-пабсаб
	transient.Publish(boardID, ts)

	return true, nil
}

// MoveShapesTransient is the resolver for the moveShapesTransient field.
func (r *mutationResolver) MoveShapesTransient(ctx context.Context, boardID string, shapes []*graph.TransientShapeInput, clientID string) (bool, error) {
	batch := &graph.TransientShapesBatch{
		ClientID: clientID,
		Shapes:   make([]*graph.TransientShape, 0, len(shapes)),
	}

	for _, s := range shapes {
		batch.Shapes = append(batch.Shapes, &graph.TransientShape{
			ID:       s.ID,
			X:        s.X,
			Y:        s.Y,
			Width:    s.Width,
			Height:   s.Height,
			ClientID: clientID,
		})
	}

	transient.PublishBatch(boardID, batch)

	return true, nil
}

// DeleteShape is the resolver for the deleteShape field.
func (r *mutationResolver) DeleteShape(ctx context.Context, boardID string, shapeID string) (bool, error) {
	storage.BoardsMu.Lock()
	defer storage.BoardsMu.Unlock()

	board, exists := storage.Boards[boardID]
	if !exists {
		return false, nil
	}

	newShapes := make([]*graph.Shape, 0, len(board.Shapes))
	var deleted *graph.Shape

	for _, s := range board.Shapes {
		if s.ID == shapeID {
			deleted = s
			continue
		}
		newShapes = append(newShapes, s)
	}

	board.Shapes = newShapes

	if deleted != nil {
		subscriptions.Publish(boardID, &graph.ShapeEvent{
			Type:     graph.ShapeEventTypeDeleted,
			Shape:    deleted,
			ClientID: "system",
		})
	}

	return deleted != nil, nil
}

// SetShapeLock is the resolver for the setShapeLock field.
func (r *mutationResolver) SetShapeLock(ctx context.Context, boardID string, shapeID string, clientID string, action graph.LockAction) (bool, error) {
	locks.Publish(boardID, &graph.LockEvent{
		ShapeID:  shapeID,
		ClientID: clientID,
		Action:   action,
	})

	return true, nil
}

// Board is the resolver for the board field.
func (r *queryResolver) Board(ctx context.Context, id string) (*graph.Board, error) {
	storage.BoardsMu.RLock()
	defer storage.BoardsMu.RUnlock()

	if board, ok := storage.Boards[id]; ok {
		return board, nil
	}

	board := &graph.Board{
		ID:     id,
		Title:  "New Board",
		Shapes: []*graph.Shape{},
	}
	storage.Boards[id] = board
	return board, nil
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (string, error) {
	return "Hello, world!", nil
}

// ShapeMoved is the resolver for the shapeMoved field.
func (r *subscriptionResolver) ShapeMoved(ctx context.Context, boardID string) (<-chan *graph.TransientShape, error) {
	ch := make(chan *graph.TransientShape, 1)
	transient.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		transient.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// ShapesMoved is the resolver for the shapesMoved field.
func (r *subscriptionResolver) ShapesMoved(ctx context.Context, boardID string) (<-chan *graph.TransientShapesBatch, error) {
	ch := make(chan *graph.TransientShapesBatch, 1)
	transient.SubscribeBatch(boardID, ch)

	go func() {
		<-ctx.Done()
		transient.UnsubscribeBatch(boardID, ch)
	}()

	return ch, nil
}

// ShapeEvents is the resolver for the shapeEvents field.
func (r *subscriptionResolver) ShapeEvents(ctx context.Context, boardID string) (<-chan *graph.ShapeEvent, error) {
	ch := make(chan *graph.ShapeEvent, 1)
	subscriptions.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		subscriptions.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// ShapeLocks is the resolver for the shapeLocks field.
func (r *subscriptionResolver) ShapeLocks(ctx context.Context, boardID string) (<-chan *graph.LockEvent, error) {
	ch := make(chan *graph.LockEvent, 1)
	locks.Subscribe(boardID, ch)

	go func() {
		<-ctx.Done()
		locks.Unsubscribe(boardID, ch)
	}()

	return ch, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
